services:
  frontend:
    build:
      context: ./facility-reservation-system/frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./facility-reservation-system/frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./facility-reservation-system/backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./facility-reservation-system/backend/app:/app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
